spring:
  application:
    name: sabor-mineiro-api
  datasource:
    url: jdbc:postgresql://localhost:5432/sabormineiro
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: never

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.sabormineiro.api: DEBUG

sabormineiro:
  app:
    jwtSecret: "mineiroSecretKeyForCollegeProject2026WithEnoughLengthToAvoidSecurityException"
    jwtExpirationMs: 86400000
